A continuous journey to get a good Linux install script

diff --git a/build/linux/dpkg/usr/local/bin/aqtion b/build/linux/dpkg/usr/local/bin/aqtion
--- a/build/linux/dpkg/usr/local/bin/aqtion
+++ b/build/linux/dpkg/usr/local/bin/aqtion
@@ -4,14 +4,29 @@ set -e
 # Check for existence of check_install
 SCRIPT_PATH="/usr/local/share/aqtion/check_install.sh"
 
-if [ ! -f ${SCRIPT_PATH} ]
+if [ $# -eq 0 ]
 then
-    echo "Installation is damaged, please reinstall this package."
-    echo "If you feel this is in error or you have reinstalled this package and you continue to get this error,"
-    echo "post a Github Issue at https://github.com/actionquake/distrib with the following:"
-    echo "uname:" $(uname -a)
-    echo "script info:" $(ls -l ${SCRIPT_PATH})
-    exit 1
+
+    if [ ! -f ${SCRIPT_PATH} ]
+    then
+        echo "Installation is damaged, please reinstall this package."
+        echo "If you feel this is in error or you have reinstalled this package and you continue to get this error,"
+        echo "post a Github Issue at https://github.com/actionquake/distrib with the following:"
+        echo "uname: $(uname -a)"
+        echo "script info: $(ls -l ${SCRIPT_PATH})"
+        exit 1
+    fi
+
+elif [ $1 = "clean" ]
+then
+    sh ${SCRIPT_PATH} clean
+elif [ $1 = "update" ]
+then
+    sh ${SCRIPT_PATH} update
+elif [ $1 = "uninstall" ]
+then
+    sh ${SCRIPT_PATH} uninstall
 else
-    sh ${SCRIPT_PATH}
+    echo "Valid arguments are 'clean', 'update' and 'uninstall'"
+    exit 1
 fi
